// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/attention/v1/attention.proto

package attentionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttentionModel_ProcessFrames_FullMethodName = "/attention.v1.AttentionModel/ProcessFrames"
)

// AttentionModelClient is the client API for AttentionModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AttentionModel processes video frames and returns attention detection results.
type AttentionModelClient interface {
	// ProcessFrames is a bidirectional streaming RPC:
	// the client streams JPEG frames, the server streams attention results.
	ProcessFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, AttentionResponse], error)
}

type attentionModelClient struct {
	cc grpc.ClientConnInterface
}

func NewAttentionModelClient(cc grpc.ClientConnInterface) AttentionModelClient {
	return &attentionModelClient{cc}
}

func (c *attentionModelClient) ProcessFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, AttentionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttentionModel_ServiceDesc.Streams[0], AttentionModel_ProcessFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, AttentionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttentionModel_ProcessFramesClient = grpc.BidiStreamingClient[FrameRequest, AttentionResponse]

// AttentionModelServer is the server API for AttentionModel service.
// All implementations must embed UnimplementedAttentionModelServer
// for forward compatibility.
//
// AttentionModel processes video frames and returns attention detection results.
type AttentionModelServer interface {
	// ProcessFrames is a bidirectional streaming RPC:
	// the client streams JPEG frames, the server streams attention results.
	ProcessFrames(grpc.BidiStreamingServer[FrameRequest, AttentionResponse]) error
	mustEmbedUnimplementedAttentionModelServer()
}

// UnimplementedAttentionModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttentionModelServer struct{}

func (UnimplementedAttentionModelServer) ProcessFrames(grpc.BidiStreamingServer[FrameRequest, AttentionResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessFrames not implemented")
}
func (UnimplementedAttentionModelServer) mustEmbedUnimplementedAttentionModelServer() {}
func (UnimplementedAttentionModelServer) testEmbeddedByValue()                        {}

// UnsafeAttentionModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttentionModelServer will
// result in compilation errors.
type UnsafeAttentionModelServer interface {
	mustEmbedUnimplementedAttentionModelServer()
}

func RegisterAttentionModelServer(s grpc.ServiceRegistrar, srv AttentionModelServer) {
	// If the following call panics, it indicates UnimplementedAttentionModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttentionModel_ServiceDesc, srv)
}

func _AttentionModel_ProcessFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AttentionModelServer).ProcessFrames(&grpc.GenericServerStream[FrameRequest, AttentionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttentionModel_ProcessFramesServer = grpc.BidiStreamingServer[FrameRequest, AttentionResponse]

// AttentionModel_ServiceDesc is the grpc.ServiceDesc for AttentionModel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttentionModel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attention.v1.AttentionModel",
	HandlerType: (*AttentionModelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessFrames",
			Handler:       _AttentionModel_ProcessFrames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/attention/v1/attention.proto",
}
