// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/attention/v1/attention.proto

package attentionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // raw JPEG bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_proto_attention_v1_attention_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attention_v1_attention_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_proto_attention_v1_attention_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AttentionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Focus         bool                   `protobuf:"varint,1,opt,name=focus,proto3" json:"focus,omitempty"`
	Theta         float64                `protobuf:"fixed64,2,opt,name=theta,proto3" json:"theta,omitempty"`
	Alpha         float64                `protobuf:"fixed64,3,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
	GazeVector    []float64              `protobuf:"fixed64,5,rep,packed,name=gaze_vector,json=gazeVector,proto3" json:"gaze_vector,omitempty"` // [x, y, z]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttentionResponse) Reset() {
	*x = AttentionResponse{}
	mi := &file_proto_attention_v1_attention_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttentionResponse) ProtoMessage() {}

func (x *AttentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attention_v1_attention_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttentionResponse.ProtoReflect.Descriptor instead.
func (*AttentionResponse) Descriptor() ([]byte, []int) {
	return file_proto_attention_v1_attention_proto_rawDescGZIP(), []int{1}
}

func (x *AttentionResponse) GetFocus() bool {
	if x != nil {
		return x.Focus
	}
	return false
}

func (x *AttentionResponse) GetTheta() float64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

func (x *AttentionResponse) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *AttentionResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *AttentionResponse) GetGazeVector() []float64 {
	if x != nil {
		return x.GazeVector
	}
	return nil
}

var File_proto_attention_v1_attention_proto protoreflect.FileDescriptor

const file_proto_attention_v1_attention_proto_rawDesc = "\n\"proto/attention/v1/attention.proto\x12\x0cattention.v1\"\"\n\x0cFrameRequest\x12\x12\n\x04data\x18\x01 \x01(\x0cR\x04data\"\x92\x01\n\x11AttentionResponse\x12\x14\n\x05focus\x18\x01 \x01(\x08R\x05focus\x12\x14\n\x05theta\x18\x02 \x01(\x01R\x05theta\x12\x14\n\x05alpha\x18\x03 \x01(\x01R\x05alpha\x12\x1a\n\x08distance\x18\x04 \x01(\x01R\x08distance\x12\x1f\n\x0bgaze_vector\x18\x05 \x03(\x01R\ngazeVector2b\n\x0eAttentionModel\x12P\n\rProcessFrames\x12\x1a.attention.v1.FrameRequest\x1a\x1f.attention.v1.AttentionResponse(\x010\x01B6Z4attention-service/pkg/proto/attention/v1;attentionv1b\x06proto3"

var (
	file_proto_attention_v1_attention_proto_rawDescOnce sync.Once
	file_proto_attention_v1_attention_proto_rawDescData []byte
)

func file_proto_attention_v1_attention_proto_rawDescGZIP() []byte {
	file_proto_attention_v1_attention_proto_rawDescOnce.Do(func() {
		file_proto_attention_v1_attention_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_attention_v1_attention_proto_rawDesc), len(file_proto_attention_v1_attention_proto_rawDesc)))
	})
	return file_proto_attention_v1_attention_proto_rawDescData
}

var file_proto_attention_v1_attention_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_attention_v1_attention_proto_goTypes = []any{
	(*FrameRequest)(nil),      // 0: attention.v1.FrameRequest
	(*AttentionResponse)(nil), // 1: attention.v1.AttentionResponse
}
var file_proto_attention_v1_attention_proto_depIdxs = []int32{
	0, // 0: attention.v1.AttentionModel.ProcessFrames:input_type -> attention.v1.FrameRequest
	1, // 1: attention.v1.AttentionModel.ProcessFrames:output_type -> attention.v1.AttentionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_attention_v1_attention_proto_init() }
func file_proto_attention_v1_attention_proto_init() {
	if File_proto_attention_v1_attention_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_attention_v1_attention_proto_rawDesc), len(file_proto_attention_v1_attention_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_attention_v1_attention_proto_goTypes,
		DependencyIndexes: file_proto_attention_v1_attention_proto_depIdxs,
		MessageInfos:      file_proto_attention_v1_attention_proto_msgTypes,
	}.Build()
	File_proto_attention_v1_attention_proto = out.File
	file_proto_attention_v1_attention_proto_goTypes = nil
	file_proto_attention_v1_attention_proto_depIdxs = nil
}
