services:
  kafka:
    image: bitnami/kafka:latest
  redis: 
    image: redis:8.2.5-bookworm
  postgres: 
    image: postgres:16.13-bookworm
  attention-model:
    build:
      context: ./attention-model
    ports:
      - "8765:8765"
    restart: unless-stopped
  attention-service:
    image: scratch
  analytics-service:
    image: scratch