# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attention/v1/attention.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61ttention/v1/attention.proto\x12\x0c\x61ttention.v1\"\x1c\n\x0c\x46rameRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"g\n\x11\x41ttentionResponse\x12\r\n\x05\x66ocus\x18\x01 \x01(\x08\x12\r\n\x05theta\x18\x02 \x01(\x01\x12\r\n\x05\x61lpha\x18\x03 \x01(\x01\x12\x10\n\x08\x64istance\x18\x04 \x01(\x01\x12\x13\n\x0bgaze_vector\x18\x05 \x03(\x01\x32\x62\n\x0e\x41ttentionModel\x12P\n\rProcessFrames\x12\x1a.attention.v1.FrameRequest\x1a\x1f.attention.v1.AttentionResponse(\x01\x30\x01\x42\x36Z4attention-service/pkg/proto/attention/v1;attentionv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attention.v1.attention_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4attention-service/pkg/proto/attention/v1;attentionv1'
  _globals['_FRAMEREQUEST']._serialized_start=46
  _globals['_FRAMEREQUEST']._serialized_end=74
  _globals['_ATTENTIONRESPONSE']._serialized_start=76
  _globals['_ATTENTIONRESPONSE']._serialized_end=179
  _globals['_ATTENTIONMODEL']._serialized_start=181
  _globals['_ATTENTIONMODEL']._serialized_end=279
# @@protoc_insertion_point(module_scope)
