# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from attention.v1 import attention_pb2 as attention_dot_v1_dot_attention__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in attention/v1/attention_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AttentionModelStub(object):
    """AttentionModel processes video frames and returns attention detection results.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrames = channel.stream_stream(
                '/attention.v1.AttentionModel/ProcessFrames',
                request_serializer=attention_dot_v1_dot_attention__pb2.FrameRequest.SerializeToString,
                response_deserializer=attention_dot_v1_dot_attention__pb2.AttentionResponse.FromString,
                _registered_method=True)


class AttentionModelServicer(object):
    """AttentionModel processes video frames and returns attention detection results.
    """

    def ProcessFrames(self, request_iterator, context):
        """ProcessFrames is a bidirectional streaming RPC:
        the client streams JPEG frames, the server streams attention results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttentionModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessFrames,
                    request_deserializer=attention_dot_v1_dot_attention__pb2.FrameRequest.FromString,
                    response_serializer=attention_dot_v1_dot_attention__pb2.AttentionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'attention.v1.AttentionModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('attention.v1.AttentionModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttentionModel(object):
    """AttentionModel processes video frames and returns attention detection results.
    """

    @staticmethod
    def ProcessFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/attention.v1.AttentionModel/ProcessFrames',
            attention_dot_v1_dot_attention__pb2.FrameRequest.SerializeToString,
            attention_dot_v1_dot_attention__pb2.AttentionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
